const airports=[
 {code:'SAN',name:'San Diego',drive:2.0,fare:236,dates:'Oct 10–15',stops:'Nonstop',park:92,fuel:44},
 {code:'LAX',name:'Los Angeles',drive:3.7,fare:198,dates:'Oct 9–14',stops:'Nonstop',park:126,fuel:72},
 {code:'PHX',name:'Phoenix',drive:3.3,fare:224,dates:'Oct 11–16',stops:'Nonstop',park:88,fuel:66},
 {code:'PSP',name:'Palm Springs',drive:2.2,fare:272,dates:'Oct 8–13',stops:'1 stop',park:76,fuel:48},
 {code:'LAS',name:'Las Vegas',drive:4.2,fare:217,dates:'Oct 10–15',stops:'Nonstop',park:82,fuel:83},
 {code:'IPL',name:'Imperial',drive:.15,fare:386,dates:'Oct 9–14',stops:'1 stop',park:36,fuel:5}
];
const list=document.querySelector('#airports');
airports.forEach((a,i)=>{const d=document.createElement('label');d.className='airport';d.innerHTML=`<input type="checkbox" data-code="${a.code}" ${i<5?'checked':''}><div><strong>${a.code} — ${a.name}</strong><small>Approx. ${a.drive<1?Math.round(a.drive*60)+' min':a.drive+' hr'} drive</small></div>`;list.appendChild(d)});
function money(n){return '$'+Math.round(n).toLocaleString()}
function run(){const t=+document.querySelector('#travelers').value;const chosen=[...document.querySelectorAll('.airport input:checked')].map(x=>x.dataset.code);let rows=airports.filter(a=>chosen.includes(a.code)).map(a=>({...a,total:a.fare*t+a.park+a.fuel}));if(!rows.length){alert('Choose at least one departure airport.');return}const lowFare=[...rows].sort((a,b)=>a.fare-b.fare)[0],best=[...rows].sort((a,b)=>a.total-b.total)[0],short=[...rows].sort((a,b)=>a.drive-b.drive)[0];document.querySelector('#recTitle').textContent=`${best.name} (${best.code}) may be your best overall value.`;document.querySelector('#recText').textContent=`Its simulated fare is ${money(best.fare)} per person. After adding estimated driving and parking, the trip comes to about ${money(best.total)} for ${t} traveler${t>1?'s':''}. Compare that with ${lowFare.code}, which has the lowest airfare at ${money(lowFare.fare)} per person.`;document.querySelector('#party').textContent=`Estimated totals for ${t} traveler${t>1?'s':''}`;
const ins=[['Lowest airfare',`${lowFare.code} • ${money(lowFare.fare)}/person`],['Best overall',`${best.code} • ${money(best.total)} total`],['Shortest drive',`${short.code} • ${short.drive<1?Math.round(short.drive*60)+' min':short.drive+' hr'}`],['Date opportunity','Shift 1 day • save up to $76/person']];document.querySelector('#insights').innerHTML=ins.map(x=>`<div class="insight"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');rows.sort((a,b)=>a.total-b.total);document.querySelector('#cards').innerHTML=rows.map(a=>`<div class="flight-card ${a.code===best.code?'best':''}"><div><small>Departure airport</small><strong>${a.code} — ${a.name}</strong>${a.code===best.code?'<span class="badge">BEST VALUE</span>':''}</div><div><small>Best dates</small><strong>${a.dates}</strong></div><div><small>Fare/person</small><strong>${money(a.fare)}</strong></div><div><small>Stops</small><strong>${a.stops}</strong></div><div><small>Drive</small><strong>${a.drive<1?Math.round(a.drive*60)+' min':a.drive+' hr'}</strong></div><div><small>Est. trip cost</small><strong>${money(a.total)}</strong></div><button class="view" onclick="alert('Prototype only — live flight details will be added after API integration.')">View flights</button></div>`).join('');document.querySelector('#savingText').textContent=`In the demo data, moving your departure by one day can reduce airfare by as much as $76 per traveler — about ${money(76*t)} for your party. A live version would scan the full date window automatically and surface these changes.`;document.querySelector('#results').classList.remove('hidden');document.querySelector('#results').scrollIntoView({behavior:'smooth'});}
document.querySelector('#searchBtn').addEventListener('click',run);
